### ISSUE TITLE
Outdent doesn't work

### ISSUE THREAD

**Issue by geoffoliver** [PollRobots/vim-monaco#2]
Not sure if "outdent" is the right name, but highlighting a line and hitting the less than (`<`) doesn't move the selected line to the left by a tabstop. The indent (greater than (`>`)) works perfect, though.

**Comment by PollRobots** [comment]
Thanks for the issue! Indent wasn't working at some point, so this doesn't seem entirely surprising. There's some subtlety in the interaction with Monaco. I'll take a look
